create table public.book_preorders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  first_name text not null,
  last_name text not null,
  email text not null,
  quantity integer not null,
  delivery_method text not null,
  street text,
  postal_code text,
  city text,
  payment_method text not null,
  message text,
  constraint book_preorders_quantity_check check (quantity >= 1 and quantity <= 20),
  constraint book_preorders_delivery_method_check check (
    delivery_method in ('presentation', 'pickup_solingen', 'shipping_de')
  ),
  constraint book_preorders_payment_method_check check (
    payment_method in ('paypal', 'bank_transfer')
  ),
  constraint book_preorders_address_consistency_check check (
    (
      delivery_method = 'shipping_de'
      and street is not null
      and btrim(street) <> ''
      and postal_code is not null
      and btrim(postal_code) <> ''
      and city is not null
      and btrim(city) <> ''
    )
    or (
      delivery_method <> 'shipping_de'
      and street is null
      and postal_code is null
      and city is null
    )
  )
);

alter table public.book_preorders enable row level security;

revoke all on table public.book_preorders from public;
revoke all on table public.book_preorders from anon, authenticated;
grant all on table public.book_preorders to service_role;

revoke all on sequence public.book_preorders_id_seq from public;
revoke all on sequence public.book_preorders_id_seq from anon, authenticated;
grant usage, select on sequence public.book_preorders_id_seq to service_role;
